---
name: CI registryauth ðŸ§¹
on:
    push:
        branches:
            - main
            - master
        paths:
            - registryauth/**/*.go
    pull_request:
        paths:
            - registryauth/**/*.go
    workflow_dispatch:

permissions:
    contents: read
    pull-requests: read
    checks: write

defaults:
    run:
        working-directory: registryauth

jobs:
    dagger-linter:
        strategy:
            matrix:
                go: ['1.22']
                dagversion: [0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 0.12.6, 0.12.7]
        name: Lint registryauth on ${{ matrix.os }} with Dagger ${{ matrix.dagversion }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: ${{ matrix.go }}
            - name: Dagger Develop on Module ðŸ“¦ with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v6
              with:
                  verb: develop
                  module: registryauth
                  version: ${{ matrix.dagversion }}
                  cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Dagger Develop on Test Module ðŸ§ª with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v6
              with:
                  verb: develop
                  module: registryauth/tests
                  version: ${{ matrix.dagversion }}
                  cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Dagger Develop on Examples Module for Go ðŸ“„ with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v6
              with:
                  verb: develop
                  module: registryauth/examples/go
                  version: ${{ matrix.dagversion }}
                  cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Dagger Call on Module ðŸ“¦ with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v6
              with:
                  verb: call
                  module: registryauth
                  version: ${{ matrix.dagversion }}
                  cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Dagger Call on Test Module ðŸ§ª with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v6
              with:
                  verb: call
                  module: registryauth/tests
                  version: ${{ matrix.dagversion }}
                  cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Dagger Call on Test Examples/Go Module ðŸ“„ with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v6
              with:
                  verb: call
                  module: registryauth/examples/go
                  version: ${{ matrix.dagversion }}
                  cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    golangci-lint:
        strategy:
            matrix:
                go: ['1.22']
        name: GolangCI-Lint for registryauth
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: ${{ matrix.go }}

      # Dagger main module ðŸ“¦ (develop & golang ci-lint)
            - name: Dagger Develop on Module ðŸ“¦ registryauth with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v6
              with:
                  verb: develop
                  module: registryauth
                  version: ${{ matrix.dagversion }}
                  cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Install golangci-lint using curl
            - name: Install golangci-lint
              run: |
                curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest
                sudo mv ./bin/golangci-lint /usr/local/bin/golangci-lint

            - name: Run golangci-lint on registryauth ðŸ“¦
              run: |
                golangci-lint run --config=../.golangci.yml --verbose

      # Dagger test module ðŸ§ª (develop & golang ci-lint)
            - name: Dagger Develop on Module tests ðŸ§ª registryauth with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v6
              with:
                  verb: develop
                  module: registryauth/tests
                  version: ${{ matrix.dagversion }}
                  cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Run golangci-lint on registryauth/tests ðŸ§ª
              run: |
                cd tests
                ls -ltrah
                golangci-lint run --config=../../.golangci.yml --verbose

      # Dagger examples (go) module ðŸ“„ (develop & golang ci-lint)
            - name: Dagger Develop on Module Examples/Go ðŸ“„ registryauth with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v6
              with:
                  verb: develop
                  module: registryauth/examples/go
                  version: ${{ matrix.dagversion }}
                  cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Run golangci-lint on registryauth/examples/go ðŸ“„ (develop & golang ci-lint)
              run: |
                cd examples/go
                ls -ltrah
                golangci-lint run --config=../../../.golangci.yml --verbose

    module-test:
        strategy:
            matrix:
                go: ['1.22']
                dagversion: [0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 0.12.6, 0.12.7]
        needs: [dagger-linter, golangci-lint]
        name: Run Tests ðŸ§ª in registryauth on ${{ matrix.os }} with Dagger ${{ matrix.dagversion }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: ${{ matrix.go }}
            - name: Dagger Develop on Module ðŸ“¦ with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v6
              with:
                  verb: develop
                  module: registryauth
                  version: ${{ matrix.dagversion }}
                  cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Dagger Develop on Test Module ðŸ§ª with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v6
              with:
                  verb: develop
                  module: registryauth/tests
                  version: ${{ matrix.dagversion }}
                  cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Running Tests ðŸ’£ in registryauth on ${{ matrix.os }} with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v6
              with:
                  verb: call
                  args: test-all
                  module: registryauth/tests
                  version: ${{ matrix.dagversion }}
                  cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    registryauth-recipes-go:
        strategy:
            matrix:
                go: ['1.22']
                dagversion: [0.12.7]
        needs: [dagger-linter, golangci-lint]
        name: Run recipes ðŸ¥— in registryauth/examples/go on ${{ matrix.os }} with Dagger ${{ matrix.dagversion }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: ${{ matrix.go }}
            - name: Dagger Develop on Module Examples ðŸ“„ with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v6
              with:
                  verb: develop
                  module: registryauth/examples/go
                  version: ${{ matrix.dagversion }}
                  cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Running Recipes all recipes ðŸ’£ in registryauth/examples/go on ${{ matrix.os }} with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v6
              with:
                  verb: call
                  args: all-recipes
                  module: registryauth/examples/go
                  version: ${{ matrix.dagversion }}
                  cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
