name: CI tflinter ðŸ§¹
on:
  push:
    branches:
      - main
      - master
    paths:
      - tflinter/**/*.go
  pull_request:
    paths:
      - tflinter/**/*.go
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: read
  checks: write
defaults:
  run:
    working-directory: tflinter
env:
  DAGGER_VERSION_EXAMPLES_GO: 0.13.7
jobs:
  dagger-linter:
    strategy:
      matrix:
        go: ["1.22"]
        dagversion: [0.13.6, 0.13.7]
    name: Lint tflinter on ${{ matrix.go }} with Dagger ${{ matrix.dagversion }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Dagger Develop on Module ðŸ“¦ with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: tflinter
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dagger Develop on Test Module ðŸ§ª with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: tflinter/tests
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dagger Develop on Examples Module for Go ðŸ“„ with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: tflinter/examples/go
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dagger Call on Module ðŸ“¦ with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          module: tflinter
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dagger Call on Test Module ðŸ§ª with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          module: tflinter/tests
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dagger Call on Test Examples/Go Module ðŸ“„ with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          module: tflinter/examples/go
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  golangci-lint:
    strategy:
      matrix:
        go: ["1.22"]
    name: GolangCI-Lint for tflinter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      # Dagger main module ðŸ“¦ (develop & golang ci-lint)
      - name: Dagger Develop on Module ðŸ“¦ tflinter with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: tflinter
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Install golangci-lint using curl
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest
          sudo mv ./bin/golangci-lint /usr/local/bin/golangci-lint
      - name: Run golangci-lint on tflinter ðŸ“¦
        run: |
          golangci-lint run --config=../.golangci.yml --verbose
      # Dagger test module ðŸ§ª (develop & golang ci-lint)
      - name: Dagger Develop on Module tests ðŸ§ª tflinter with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: tflinter/tests
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run golangci-lint on tflinter/tests ðŸ§ª
        run: |
          cd tests
          ls -ltrah
          golangci-lint run --config=../../.golangci.yml --verbose
      # Dagger examples (go) module ðŸ“„ (develop & golang ci-lint)
      - name: Dagger Develop on Module Examples/Go ðŸ“„ tflinter with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: tflinter/examples/go
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run golangci-lint on tflinter/examples/go ðŸ“„ (develop & golang ci-lint)
        run: |
          cd examples/go
          ls -ltrah
          golangci-lint run --config=../../../.golangci.yml --verbose
  tflinter-test:
    strategy:
      matrix:
        go: ["1.22"]
        dagversion: [0.13.6, 0.13.7]
    needs: [dagger-linter, golangci-lint]
    name: Run Tests ðŸ§ª in tflinter on ${{ matrix.go }} with Dagger ${{ matrix.dagversion }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Dagger Develop on Module ðŸ“¦ with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: tflinter
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Dagger Develop on Test Module ðŸ§ª with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: tflinter/tests
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Running Tests ðŸ’£ in tflinter on ${{ matrix.go }} with Dagger ${{ matrix.dagversion }}
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          args: test-all
          module: tflinter/tests
          version: ${{ matrix.dagversion }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  tflinter-recipes-go:
    strategy:
      matrix:
        go: ["1.22"]
        dagversion: [0.13.6, 0.13.7]
    needs: [dagger-linter, golangci-lint]
    name: Run recipes ðŸ¥— in tflinter/examples/go on ${{ matrix.go }} with Dagger ${{ matrix.dagversion }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Dagger Develop on Module Examples ðŸ“„
        uses: dagger/dagger-for-github@v6
        with:
          verb: develop
          module: tflinter/examples/go
          version: ${{ env.DAGGER_VERSION_EXAMPLES_GO }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Running Recipes all recipes ðŸ’£ in tflinter/examples/go
        uses: dagger/dagger-for-github@v6
        with:
          verb: call
          args: all-recipes
          module: tflinter/examples/go
          version: ${{ env.DAGGER_VERSION_EXAMPLES_GO }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
