---
name: Gotest CI ðŸ§¹
on:
    push:
        branches:
            - main
            - master
        paths:
            - gotest/**/*.go
    pull_request:
        paths:
            - gotest/**/*.go
    workflow_dispatch:

permissions:
    contents: read
    pull-requests: read
    checks: write

defaults:
    run:
        working-directory: gotest

jobs:
    linter:
        strategy:
            matrix:
                go: ['1.22']
                dagversion: [0.11.6, 0.11.7]
        name: Lint gotest on ${{ matrix.os }} with Dagger ${{ matrix.dagversion }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: ${{ matrix.go }}
            - name: Dagger Develop on Module ðŸ“¦ with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v5
              with:
                  verb: develop
                  module: gotest
                  version: ${{ matrix.dagversion }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Dagger Develop on Test Module ðŸ§ª with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v5
              with:
                  verb: develop
                  module: gotest/tests
                  version: ${{ matrix.dagversion }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Dagger Call on Module with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v5
              with:
                  verb: call
                  module: gotest
                  version: ${{ matrix.dagversion }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Dagger Call on Test Module ðŸ§ª with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v5
              with:
                  verb: call
                  module: gotest/tests
                  version: ${{ matrix.dagversion }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    golangci-lint:
        strategy:
            matrix:
                go: ['1.22']
        name: GolangCI-Lint for gotest
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: ${{ matrix.go }}
            - name: Dagger Develop on Module ðŸ“¦ gotest with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v5
              with:
                  verb: develop
                  module: gotest
                  version: ${{ matrix.dagversion }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Run golangci-lint on gotest ðŸ“¦
              uses: golangci/golangci-lint-action@v6
              with:
                  version: v1.58
                  args: --config .golangci.yml ./gotest/dagger
            - name: Dagger Develop on Module tests ðŸ§ª gotest with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v5
              with:
                  verb: develop
                  module: gotest/tests
                  version: ${{ matrix.dagversion }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Run golangci-lint on gotest/tests ðŸ§ª
              uses: golangci/golangci-lint-action@v6
              with:
                  version: v1.58
                  args: --config .golangci.yml ./gotest/tests/dagger

    module-test:
        strategy:
            matrix:
                go: ['1.22']
                dagversion: [0.11.6, 0.11.7]
        needs: [linter, golangci-lint]
        name: Run Tests ðŸ§ª in gotest on ${{ matrix.os }} with Dagger ${{ matrix.dagversion }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version: ${{ matrix.go }}
            - name: Dagger Develop on Module ðŸ“¦ with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v5
              with:
                  verb: develop
                  module: gotest
                  version: ${{ matrix.dagversion }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Dagger Develop on Test Module ðŸ§ª with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v5
              with:
                  verb: develop
                  module: gotest/tests
                  version: ${{ matrix.dagversion }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Running Tests ðŸ’£ in gotest on ${{ matrix.os }} with Dagger ${{ matrix.dagversion }}
              uses: dagger/dagger-for-github@v5
              with:
                  verb: call
                  args: test-all
                  module: gotest/tests
                  version: ${{ matrix.dagversion }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
